---
bot_id: "{{BOT_ID}}"
gpu_id: {{GPU_ID}}
port: {{PORT}}
status: initialized
created: {{TIMESTAMP}}

# Model Runtime
model:
  name: "granite4:micro-h"
  quant: "Q4"
  context_length: 4096

# Local Memory
memory:
  vectors: []
  capacity: 1000
  eviction_policy: "FIFO"

# Gossip Network
network:
  entry_nodes: {{ENTRY_NODES}}
  neighbors: []
  gossip_interval: 1.0

# Performance
performance:
  avg_latency_ms: 0
  total_requests: 0
  errors: 0
  uptime_seconds: 0
